<?php
// Authentication check
$isLoggedIn = isset($_SESSION['user_id']);
$userType = $isLoggedIn ? $_SESSION['user_type'] : '';
?>
<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EcoTrack - Waste Management System</title>
    <link rel="stylesheet" href="/assets/css/main.css">
    <link rel="stylesheet" href="/assets/css/animations.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
<body>
    <!-- Animated Background -->
    <div class="animated-bg"></div>
    
    <!-- Floating Particles -->
    <div class="particles-container">
        <div class="particle"></div>
        <div class="particle"></div>
        <div class="particle"></div>
        <!-- More particles generated by JS -->
    </div>
    
    <header class="glass-header">
        <div class="container">
            <div class="logo">
                <div class="logo-icon animate-spin-in">
                    <i class="fas fa-recycle"></i>
                </div>
                <h1>Eco<span>Track</span></h1>
            </div>
            
            <nav class="main-nav">
                <ul>
                    <li><a href="/index.php" class="nav-link hover-underline">Home</a></li>
                    <?php if ($isLoggedIn): ?>
                        <li><a href="/feedback.php" class="nav-link hover-underline">Report Issue</a></li>
                        <li><a href="/status.php" class="nav-link hover-underline">Track Status</a></li>
                        <li><a href="/schedule.php" class="nav-link hover-underline">Schedule</a></li>
                        <?php if ($userType === 'admin'): ?>
                            <li><a href="/admin/dashboard.php" class="nav-link hover-underline">Dashboard</a></li>
                        <?php elseif ($userType === 'waste_team'): ?>
                            <li><a href="/admin/tasks.php" class="nav-link hover-underline">My Tasks</a></li>
                        <?php endif; ?>
                    <?php endif; ?>
                </ul>
            </nav>
            
            <div class="header-actions">
                <button id="theme-toggle" class="icon-btn" aria-label="Toggle theme">
                    <i class="fas fa-moon"></i>
                </button>
                
                <?php if ($isLoggedIn): ?>
                    <div class="user-dropdown">
                        <div class="user-avatar">
                            <i class="fas fa-user-circle"></i>
                        </div>
                        <div class="dropdown-menu">
                            <div class="user-info">
                                <div class="user-name"><?php echo $_SESSION['full_name']; ?></div>
                                <div class="user-role"><?php echo ucfirst(str_replace('_', ' ', $userType)); ?></div>
                            </div>
                            <a href="profile.php" class="dropdown-item">
                                <i class="fas fa-user"></i> Profile
                            </a>
                            <a href="settings.php" class="dropdown-item">
                                <i class="fas fa-cog"></i> Settings
                            </a>
                            <a href="logout.php" class="dropdown-item">
                                <i class="fas fa-sign-out-alt"></i> Logout
                            </a>
                        </div>
                    </div>
                <?php else: ?>
                    <div class="auth-buttons">
                        <a href="login.php" class="btn btn-outline">Login</a>
                        <a href="register.php" class="btn btn-primary">Register</a>
                    </div>
                <?php endif; ?>
                
                <button class="mobile-menu-btn">
                    <i class="fas fa-bars"></i>
                </button>
            </div>
        </div>
    </header>
    
    <div class="mobile-nav">
        <!-- Mobile navigation content -->
    </div>
    
    <main class="container">